import os
import unittest
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from src.smartapply.keyword_extractor.keyword_extractor import extract_keywords_from_html

class TestKeywordExtractor(unittest.TestCase):

    def test_extract_keywords_from_html_with_valid_html(self):
        actual_keywords = extract_keywords_from_html(os.path.join(os.path.dirname(__file__), "resources", "test_data.html"))
        expected_keywords = {'Anfrage', 'Beratung', 'weiterempfehlen', 'Remote', 'stehen', 'Projektbeschreibung', '+7', 'Präsenztermin', 'Einstellen', 'Bewerbungsformular', 'bewerben', 'Branche', 'Fokus', 'Transformationsumfeld', 'Transformation', 'Squad', 'Kenntnis', 'Team', 'cross-funktionaler', 'Ort', 'Textbaustein', '×', 'websit', 'Zeremonie', 'Nachricht', 'Projekt', 'verwandt', 'Kontrollziel', 'Branchenerfahrung', 'Nachweis', 'Demonstrations-Fähigkeit', 'Teamentwicklung', 'Leistungserbringung', 'unterstützen', 'arbeitspaketverantwortliche', 'Freiberuflich', 'deutsch', 'Zertifizierung', 'überprüfen', 'IT-Programm-', 'vorsehen', 'Moderationserfahrung', 'Umfang', 'anlegen', 'Darstellung', 'wählen', 'Lieferobjekt', 'Dokumentation', 'Option', 'Optimierung', 'upgraden', 'empfehlen', 'Einsatzort', 'Kontaktinformation', 'Projektausschreibung', 'Initiative', 'Erfahrung', 'Fahren', 'SAFE_Agilist.pdf', 'Start', 'Angabe', 'anzeigen', 'Maßnahme', 'Premium-Mitgliedschaft', 'KI-Bewerbung', 'nachweisen', 'Mengershause', 'gestalten', 'COBIT', 'Begleitung', 'Land', 'Name', 'Profil', 'Empfänger', 'Aufgabe', 'erhalten', 'Job', 'E-Mail-Adresse', 'verbrauchen', 'Textblock', 'Pflege', 'Ende', 'Verlängerung', 'Methodenmodell', 'onshore', 'Zeitraum', 'Anwendung', 'Projektreferenz', 'Auslastung', 'Telekommunikationsunternehmen', 'Aufbereitung', 'AG', 'Formular', 'IT', '%', 'Thema', 'Upgrade', 'Agil', 'Hinweis', 'Schreiben', 'SAFe', 'Dauer', 'Telefon', 'Visitenkarte', 'ergreifen', 'Prozeß', 'Umfeld', 'Muss-Kriteri', 'melden', 'Simple', 'Soll-Kriterien', 'Management', 'Technologie', 'Text', 'Schlagwort', 'suchen', 'Woche', 'Konfliktlösung', 'Einreichung', 'bewerten', 'generieren', 'Rückmeldung', 'E-Mail', 'Firma', 'eingetragen', 'Ansprechpartner', 'Verständnis', 'Framework', 'Freelancerverzeichnis', 'Beschreibung', 'iBSC', '+6', 'Methodologie', 'passen', 'Vorteil', 'Regelfall', 'Senior', 'Projektsprache', 'Anschreib', 'Monat', 'Rahmenbedingung', 'Bearbeitung', 'Erstellung', 'Bewerbung', 'Unternehmenstransformation', 'Kunde', 'Merkliste', 'bestehen', 'senden', 'Strukturierung', 'Vertragsart', 'applikationen', '15:39', 'genügen', 'Methode', 'Application', 'Projektmanagement', 'Multiprojektvorgehen', 'Jahr', 'Zugriff', 'Partnerangebot', 'Mund', 'Empfehlung', 'Zusammenhang', 'Transportation', 'Trefferliste', 'versenden', 'Manager', 'Tag', 'Anwendungsmanagement', 'Erläuterung', 'Standardisierung', 'Bestätigung', 'Transformationsprojekt', 'Datei-Anlag', 'Unterstützung', 'Einsatzart', 'Product', 'Asset-Owner', 'GmbH', 'danken', 'vorgehen', 'Scrum', 'Definition', 'Anschreibe', 'Prozessoptimierung', 'Bedarf', 'Zusendung', 'Consultant', 'Bewerbungstext'}
        # print(f"actual_keywords = {actual_keywords}")
        self.assertEqual(actual_keywords, expected_keywords)

if __name__ == '__main__':
    unittest.main()
